// PCG-XSL-RR-128/64 ("pcg64") — the normative PRNG for stochastic
// calculations (protocol §VIII.8, RFC 0005).
//
// The whole point of specifying an algorithm rather than reaching for a
// library is that the seed and the algorithm together ARE the determinism
// contract. Two conforming hosts given the same seed must produce the same
// sample sequence, or a stochastic calc is not reproducible and the format's
// core promise — that the numbers follow from the inputs — stops holding for
// anything with uncertainty in it. A library dependency would make its version
// part of that contract; forty lines here do not.
//
// BigInt rather than a 64-bit-pair trick: the state is 128 bits, and hand-rolled
// limb arithmetic is exactly where an implementation quietly diverges from
// every other one. Speed is not the constraint — the sample cap is 100,000
// draws, which BigInt handles in milliseconds.
//
// ─────────────────────────────────────────────────────────────────────────────
// VERIFICATION GAP, stated rather than buried:
//
// The test vector in `prng.test.ts` and in `conformance/stochastic/` was
// generated BY THIS IMPLEMENTATION. It proves self-consistency across runs and
// platforms; it does NOT prove agreement with the reference C implementation at
// pcg-random.org. The algorithm below is written from the published
// specification, but nobody has diffed its output against O'Neill's.
//
// That check is cheap and has not been done. Until it is, an implementer
// porting this to another language should port THIS code, not write pcg64 from
// the paper and assume the two agree. The steps to close it are in
// docs/handoff/HUMAN-verify-pcg64-vector.md; RFC 0005 records the same caveat.
// ─────────────────────────────────────────────────────────────────────────────

const MASK_128 = (1n << 128n) - 1n;
const MASK_64 = (1n << 64n) - 1n;

/** PCG64 multiplier, from the reference implementation. */
const MULTIPLIER = 47026247687942121848144207491837523525n;
/** PCG64 default stream increment. */
const INCREMENT = 117397592171526113268558934119004209487n;

/** The algorithm identifier a result echoes back, so a reader can tell what produced it. */
export const PRNG_ALGORITHM = 'pcg-xsl-rr-128-64' as const;

export class Pcg64 {
  private state: bigint;

  /**
   * Seeded exactly as the reference `srandom` does: zero the state, step it,
   * add the seed, step again. Reproducing that sequence matters more than it
   * looks — a host that merely assigned the seed to the state would produce a
   * different stream from every correct implementation, while still being
   * perfectly deterministic and therefore passing any self-consistency test.
   */
  constructor(seed: bigint | number) {
    this.state = 0n;
    this.step();
    this.state = (this.state + (BigInt(seed) & MASK_128)) & MASK_128;
    this.step();
  }

  private step(): void {
    this.state = (this.state * MULTIPLIER + INCREMENT) & MASK_128;
  }

  /** One 64-bit output. */
  nextUint64(): bigint {
    this.step();
    // XSL: fold the high half into the low half.
    const xorshifted = ((this.state >> 64n) ^ this.state) & MASK_64;
    // RR: rotate right by the top six bits of the state.
    const rot = Number((this.state >> 122n) & 63n);
    if (rot === 0) return xorshifted;
    return ((xorshifted >> BigInt(rot)) | (xorshifted << BigInt(64 - rot))) & MASK_64;
  }

  /**
   * A double in `[0, 1)`, using the top 53 bits — the exact width of a double's
   * mantissa.
   *
   * 53 and not 64: dividing a 64-bit integer by 2^64 rounds, so two integers
   * differing in their low bits can map to the same double while a third maps
   * to `1.0`. Taking 53 bits and dividing by 2^53 is exact for every input, so
   * the result is a faithful function of the draw and never reaches 1.0.
   */
  nextDouble(): number {
    return Number(this.nextUint64() >> 11n) / 9007199254740992; // 2^53
  }
}

// ─── Inverse-CDF sampling ────────────────────────────────────────────────────
//
// Every distribution is sampled by inverting its CDF at a uniform draw, and
// that choice is about cross-implementation determinism rather than elegance.
//
// IEEE 754 exactly specifies `+ - * /` and `sqrt`. It does NOT specify `log`,
// `exp`, `sin`, or `cos` — those are libm functions whose last-place results
// differ between platforms and versions. So the textbook normal samplers are
// unusable: Box-Muller needs `log` and `cos`, Marsaglia polar needs `log`.
// Either produces samples that agree to about fifteen digits across hosts and
// disagree in the sixteenth, which is how "reproducible" becomes "reproducible
// on my machine".
//
// This buys exactness for two of the three distributions, and the third is
// honest about not having it — see `inverseNormalCdf`.

/** A uniform draw on `[min, max)`. Arithmetic only, so bit-exact everywhere. */
export function sampleUniform(u: number, min: number, max: number): number {
  return min + u * (max - min);
}

/**
 * A triangular draw. Uses `sqrt`, which IEEE 754 specifies exactly, so this is
 * bit-exact everywhere too.
 *
 * Worth having beyond its own merits: the asset-class default tables already
 * carry `low`/`central`/`high`, which are exactly a triangular distribution's
 * parameters. An adopter can turn the existing napkin-mode ranges into
 * distributions without inventing any numbers (RFC 0005 §Range types).
 */
export function sampleTriangular(u: number, min: number, mode: number, max: number): number {
  const span = max - min;
  if (span === 0) return min;
  const split = (mode - min) / span;
  if (u < split) return min + Math.sqrt(u * span * (mode - min));
  return max - Math.sqrt((1 - u) * span * (max - mode));
}

/**
 * Inverse standard-normal CDF — Acklam's rational approximation.
 *
 * **This one is not bit-exact across platforms, and the spec says so.** The
 * central region (0.02425 ≤ p ≤ 0.97575, about 95% of draws) is arithmetic
 * only and therefore exact. Both tails need `log`, which no standard requires
 * to be correctly rounded, so two hosts can disagree in the last place there.
 *
 * The alternative was to reject the normal distribution outright, and that is
 * worse: it is the distribution adopters actually reach for. So it ships, the
 * limitation is normative (§VIII.8.4), and conformance compares normal-derived
 * summaries at a stated tolerance while `uniform` and `triangular` are pinned
 * exactly. Naming which distributions are exact is more useful than a blanket
 * tolerance that hides the difference.
 *
 * Relative error of the approximation itself is about 1.15e-9.
 */
export function inverseNormalCdf(p: number): number {
  if (!(p > 0 && p < 1)) {
    throw new RangeError(`inverseNormalCdf expects p in (0, 1), got ${p}`);
  }

  const a1 = -3.969683028665376e1;
  const a2 = 2.209460984245205e2;
  const a3 = -2.759285104469687e2;
  const a4 = 1.38357751867269e2;
  const a5 = -3.066479806614716e1;
  const a6 = 2.506628277459239;

  const b1 = -5.447609879822406e1;
  const b2 = 1.615858368580409e2;
  const b3 = -1.556989798598866e2;
  const b4 = 6.680131188771972e1;
  const b5 = -1.328068155288572e1;

  const c1 = -7.784894002430293e-3;
  const c2 = -3.223964580411365e-1;
  const c3 = -2.400758277161838;
  const c4 = -2.549732539343734;
  const c5 = 4.374664141464968;
  const c6 = 2.938163982698783;

  const d1 = 7.784695709041462e-3;
  const d2 = 3.224671290700398e-1;
  const d3 = 2.445134137142996;
  const d4 = 3.754408661907416;

  const P_LOW = 0.02425;
  const P_HIGH = 1 - P_LOW;

  if (p < P_LOW) {
    const q = Math.sqrt(-2 * Math.log(p));
    return (
      (((((c1 * q + c2) * q + c3) * q + c4) * q + c5) * q + c6) /
      ((((d1 * q + d2) * q + d3) * q + d4) * q + 1)
    );
  }
  if (p > P_HIGH) {
    const q = Math.sqrt(-2 * Math.log(1 - p));
    return -(
      (((((c1 * q + c2) * q + c3) * q + c4) * q + c5) * q + c6) /
      ((((d1 * q + d2) * q + d3) * q + d4) * q + 1)
    );
  }
  const q = p - 0.5;
  const r = q * q;
  return (
    ((((((a1 * r + a2) * r + a3) * r + a4) * r + a5) * r + a6) * q) /
    (((((b1 * r + b2) * r + b3) * r + b4) * r + b5) * r + 1)
  );
}

/** A normal draw, via {@link inverseNormalCdf}. */
export function sampleNormal(u: number, mean: number, stddev: number): number {
  return mean + stddev * inverseNormalCdf(u);
}
